version: "3.8"
services:
  copy-trader-redis:
    image:
      copy-trader-redis
    expose:
      - "6379"
    volumes:
      - ./.redis_root:/var/lib/redis

  copy-trader:
    image:
      copy-trader
    depends_on:
      - copy-trader-redis
    environment:
      - REDIS_ENDPOINT=redis://copy-trader-redis:6379
    ports:
      - "40404:40404"
      - "51585:51585"
    volumes:
      - ./:/usr/src/app
